### PR TITLE
Update index.tsx

### PR DESCRIPTION
**Pull request by KendallDoesCoding**
Instead of saying There you have it, it's better to say project coming soon, so people who come across this project, will know what's up, otherwise they may think it's not working or something.

### CODE REVIEW

**Comment by joaogelado** [comment]
Because (for now) this is a personal project, I will not accept prs ok?

**Comment by KendallDoesCoding** [comment]
> Because (for now) this is a personal project, I will not accept prs ok?

Uh ok...

**Comment by joaogelado** [comment]
know its strange haha
probably later i'll accept

**Comment by KendallDoesCoding** [comment]
> know its strange haha probably later i'll accept

Ok, I'll reopen when you wanna accept.

**Pull request closed without merging**
